export const MARK_NEW_LOADED_YEAR = 'MARK_NEW_LOADED_YEAR'
export const SET_RANGE_TO_SHOW = 'SET_RANGE_TO_SHOW'
export const RECEIVE_INCIDENTS = 'RECEIVE_INCIDENTS'
export const GET_INCIDENTS = 'GET_INCIDENTS'
