export const MARK_NEW_LOADED_YEAR = 'MARK_NEW_LOADED_YEAR'
export const SET_RANGE_TO_SHOW = 'SET_RANGE_TO_SHOW'
export const RECEIVE_INCIDENTS_OF_A_YEAR = 'RECEIVE_INCIDENTS_OF_A_YEAR'
export const GET_INCIDENTS = 'GET_INCIDENTS'
export const SET_MAP_SHOULD_UPDATE = 'SET_MAP_SHOULD_UPDATE'

export const SET_CLUSTER_INFO_ACTIVE = 'SET_CLUSTER_INFO_ACTIVE'
export const SET_CLUSTER_INFO_INACTIVE = 'SET_CLUSTER_INFO_INACTIVE'

export const SHOW_CLUSTER_INFO = 'SHOW_CLUSTER_INFO'
export const HIDE_CLUSTER_INFO = 'HIDE_CLUSTER_INFO'
